[tool.poetry]
name = "examples"
version = "0.1.0"
description = ""
authors = ["Pasquale Antonante <p.antonante@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9.0,<3.12"
langchain-community = "^0.0.17"
langchain-openai = "^0.0.5"
chromadb = "^0.4.22"
langchain-google-genai = "^0.0.6"

relari= {path = "../cli/", develop = true}
langchain = "^0.1.5"
unstructured = "^0.12.3"
tqdm = "^4.66.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
